Add optional flags to create command

diff --git a/plzvm b/plzvm
--- a/plzvm
+++ b/plzvm
@@ -19,7 +19,15 @@ usage() {
   echo
   echo "Commands"
   echo "====================================================================="
-  echo "- plzvm create <name> <iso> [disksizeMB]"
+  echo "- plzvm create <name>"
+  echo "               --iso [isopath] (required)"
+  echo "               [--ostype <ostype>] (optional)"
+  echo "               [--home <homepath>] (default: $HOME)"
+  echo "               [--hdd <size>] (default: 32gb)"
+  echo "               [--ram <size>] (default: 1gb)"
+  echo "               [--vram <size>] (default: 128mb)"
+  echo "               [--sshport <port>] (optional)"
+  echo
   echo "- plzvm delete <name>"
   echo "- plzvm open [name]"
   echo "- plzvm start [name]"
@@ -49,15 +57,6 @@ if [[ $1 = "help" || $1 = "-help" || $1 = "--help" || $1 == "-h" ]]; then
   echo
   echo "plzvm uninstall"
   echo "- Removes plzvm from /usr/local/bin/"
-  echo
-  echo "---------------------------------------------------------------------"
-  echo "Creating and deleting VMs:"
-  echo
-  echo "plzvm create foo ~/ubuntu-16.04.1-server-amd64.iso 32768"
-  echo "- Creates a new VM called \"foo\" using the iso file and disk size (in MB)"
-  echo
-  echo "plzvm delete foo"
-  echo "- Deletes the VM named \"foo\"."
   echo
   echo "---------------------------------------------------------------------"
   echo "Starting and stopping VMs:"
@@ -305,12 +304,54 @@ if [[ $1 = "delete" && $2 ]]; then
 fi
 
 
-if [[ $1 = "create" && $2 && $3 ]]; then
+getsize() {
+  pad=$(perl -e "(uc \"$1\") =~ /(\\d+)(.*)/i; print \"\$1 \$2\"")
+  pair=($pad)
+  num=${pair[0]}
+  how=${pair[1]}
+
+  if [[ $how = "GB" ]]; then num="$(($num * 1024))"
+  fi
+
+  echo $num
+}
+
+
+if [[ $1 = "create" && $2 ]]; then
+  # Define default values.
+  homefolder=$HOME
+  hddsize=$(getsize 32gb)
+  ramsize=$(getsize 1gb)
+  vramsize=$(getsize 128mb)
+
   vm=$2
-  iso=$3
+  shift 2
+
+  while [ -n "$1" ]; do
+    if [[ $1 = "--iso" ]]; then iso=$2
+    elif [[ $1 = "--ostype" ]]; then ostype=$2
+    elif [[ $1 = "--home" ]]; then homefolder=$2
+    elif [[ $1 = "--hdd" ]]; then hddsize=$(getsize $2)
+    elif [[ $1 = "--ram" ]]; then ramsize=$(getsize $2)
+    elif [[ $1 = "--vram" ]]; then vramsize=$(getsize $2)
+    elif [[ $1 = "--sshport" ]]; then sshport=$2
+    fi
+    shift 2
+  done
+
+  if ! [[ $iso ]]; then
+    echo "Error: Missing ISO"
+    echo "Please specify your ISO image using the '--iso' command line argument."
+    exit 1
+  fi
 
   if ! [[ -e $iso ]]; then
     echo "Cannot find the ISO image at $iso"
+    exit 1
+  fi
+
+  if ! [[ -d $homefolder ]]; then
+    echo "Cannot find the directory '$homefolder'"
     exit 1
   fi
 
@@ -320,43 +361,44 @@ if [[ $1 = "create" && $2 && $3 ]]; then
   # This set up is based on instructions by Lee Mendelowitz:
   # https://leemendelowitz.github.io/blog/ubuntu-server-virtualbox.html
 
-  echo "Creating new VM named \"$vm\"."
-  vboxmanage createvm --name $vm --ostype Ubuntu_64 --register
-
-  # MUST: Require the user to specify where to put the VDI file.
-  echo "Creating new disk named \"$vm.vdi\"."
-  if [[ $4 ]]; then
-    vboxmanage createmedium disk --filename $vm.vdi --size $4
+  if [[ $ostype ]]; then
+    echo "Creating new VM named \"$vm\" with ostype $ostype."
+    vboxmanage createvm --name $vm --ostype $ostype --register
   else
-    # MUST: Document what VirtualBox does when the size is omitted.
-    vboxmanage createmedium disk --filename $vm.vdi
+    echo "Creating new VM named \"$vm\" (with no ostype)."
+    vboxmanage createvm --name $vm --register
   fi
+
+  vdi="$homefolder/$vm.vdi"
+  echo "Creating new disk at \"$vdi\" with max size $hddsize MB."
+  vboxmanage createmedium disk --filename $vdi --size $hddsize
 
   echo "Creating SATA Controller."
   vboxmanage storagectl $vm --name "SATA Controller" --add sata --controller IntelAHCI
 
-  echo  "Attaching SATA Controller to $vm.vdi HDD."
-  vboxmanage storageattach $vm --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium $vm.vdi
+  echo  "Attaching SATA Controller to HDD: $vdi"
+  vboxmanage storageattach $vm --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium $vdi
 
   echo "Creating IDE Controller"
   vboxmanage storagectl $vm --name "IDE Controller" --add ide
 
-  echo "Attaching IDE Controller to $iso DVD."
+  echo "Attaching IDE Controller to DVD: $iso"
   vboxmanage storageattach $vm --storagectl "IDE Controller" --port 0 --device 0 --type dvddrive --medium $iso
 
   echo "Enable I/O APIC (required for 64-bit guest operating systems)."
   echo "Details: https://www.virtualbox.org/manual/ch03.html#settings-motherboard"
   vboxmanage modifyvm $vm --ioapic on
 
-  echo "Start with 1 GB RAM and 128 MB video memory."
-  vboxmanage modifyvm $vm --memory 1024 --vram 128
+  echo "Start with $ramsize MB RAM and $vramsize MB video memory."
+  vboxmanage modifyvm $vm --memory $ramsize --vram $vramsize
 
   echo "Use network address translation for network card #1."
   vboxmanage modifyvm $vm --nic1 nat
 
-  # MAY: Allow the user to specify which port to use for ssh access.
-  echo "Map local port 2222 to the port 22 on the VM (for ssh access)."
-  vboxmanage modifyvm $vm --natpf1 "guestssh,tcp,,2222,,22"
+  if [[ $sshport ]]; then
+    echo "Map local port $sshport to the port 22 on the VM (for ssh access)."
+    vboxmanage modifyvm $vm --natpf1 "guestssh,tcp,,$sshport,,22"
+  fi
 
   echo "Make the NAT engine use the host's resolver mechanisms to handle DNS requests."
   echo "Details: https://www.virtualbox.org/manual/ch09.html#nat-adv-dns"
